### ISSUE TITLE
"There has been an error please log back in" 

### ISSUE THREAD

**Issue by HypnoMatt** [Wynncraft/Issues#1979]
Every time I try and connect to a world it gives me the error message in the title. I have tried relogging multiple times and connecting to multiple different worlds.
![2015-06-09_18 42 00](https://cloud.githubusercontent.com/assets/12817198/8063858/6892d490-0ed7-11e5-845c-5601389fc4b1.png)

**Comment by Trixter313** [comment]
Have you tried restarting your computer and router? If none of this works, giving it a break of about an hour usually fixes the issue.

**Comment by HypnoMatt** [comment]
Yes I have tried that and it has not fixed the issue

**Comment by Trixter313** [comment]
If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thanks and we hope you enjoy your time playing Wynncraft! :)

**Comment by TheRex94** [comment]
although there is not necessarily report it is super importan /!\ I was creating my bottle and it was let go to the ground at the time of restart so that I lost liquid 5bouteille Emeraud help you I m suppli

**Comment by Trixter313** [comment]
Unfortunately Wynncraft has a very strict no refund policy so there's not much that can be done. All i can suggest is to try to be mindful of whether a restart is happening soon next time you're trading anything. Also, if you have to report any issues in the future, create a new issue rather than spamming on unrelated issues. :)

**Comment by HypnoMatt** [comment]
No I'm still getting the same issue. Could the issue be that I played with a different account a long time ago?

**Comment by Trixter313** [comment]
Wow, I'm surprised this issue has been happening to you for 11 days! Have you tried backing up your saves, resource packs, screenshots, and anything else important to you and reinstalling Minecraft?

**Comment by HypnoMatt** [comment]
Well I have no issues with any other server and if I use a different account I can play just fine. The issue only seems to be with my account. So I doubt reinstalling Minecraft will make a difference in this case

**Comment by HypnoMatt** [comment]
I'm still having this issue
