### ISSUE TITLE
Already Logged In

### ISSUE THREAD

**Issue by Socksykins** [Wynncraft/Issues#2172]
i was playing wynncraft for 30mins and then i got kicked (readout exeption) and then tried to join and now it keeps saying that im already logged in when i join a server and its been doing this for the past few hours

**Comment by Trixter313** [comment]
Have you been waiting in the lobby for the entire time? If you close Minecraft for a few minutes to an hour it should fix the issue.

**Comment by Socksykins** [comment]
i would provide a screenshot but it dosent let me drag and drop a jpg or png file

**Comment by Trixter313** [comment]
It's ok, this has been happening a lot recently.

**Comment by ohhcon** [comment]
Same things happening to me so i closed mc for 3 hours , came back , still happening.

**Comment by Trixter313** [comment]
Has the issue cleared up for the both of you two by now?

**Comment by Socksykins** [comment]
yup

**Comment by Trixter313** [comment]
If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
