### ISSUE TITLE
bugged in the spider dungeon

### ISSUE THREAD

**Issue by TheLegendOnze** [Wynncraft/Issues#2187]
Hello, today i tried to enter the spider dungeon as I jumped onto the teleporter everything went black and i cant see anything, i tried to relog but nothing happend. As i pressed random keys i droppe my bow now i stuck in the place. please help me! 
username: TheLegendOnze

**Comment by Trixter313** [comment]
Typing /die with 2+ soul points should free you.

If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by TheLegendOnze** [comment]
i got out but i lost my two spider keys and my bow -,-

**Comment by Trixter313** [comment]
Unfortunately Wynncraft has a strict no refund policy so there's not much we can do about the items.

**Comment by TheLegendOnze** [comment]
what they got lost in a bug, its not my fault that the key guy took two keys

**Comment by Trixter313** [comment]
Explain what you mean by he took 2 keys. By what you said already, you should only have one less key.

**Comment by TheLegendOnze** [comment]
i have 0 spider keys now. As i killed myself and went back into the dungeon there were no more keys in my inventory so i couldnt enter the dungeon to maybe pick up my bow

**Comment by Trixter313** [comment]
You went in the dungeon and got stuck and /died. When you went in the second time you didn't get stuck and can complete the dungeon normally do that doesn't count as a wasted key.

**Comment by TheLegendOnze** [comment]
but why i have no keys left when i got 2 before. I only used one and i didnt completed the dungeon because i have to /die. As i tried to enter the second time i couldnt enter because the villager said u need 1 key

**Comment by Trixter313** [comment]
Ah, I misread a couldn't as could in your last post. You most likely dropped a key around the same time you dropped your weapon. I'm sure if you ask other players for a key someone will give you one.

**Comment by TheLegendOnze** [comment]
I didnt dropped a key i only pressed q while i had selected my bow......

**Comment by TheLegendOnze** [comment]
now i bought a skeleton key at the key merchant near the dungeon. As i wan to enter the key collector said give me on skeleton key and my key dissappeard but i couldnt enter the dungeon

**Comment by TheLegendOnze** [comment]
now the skeleton key bugged back in my inventory and i could enter

**Comment by TheLegendOnze** [comment]
now i completed skeleton and spider dungeon but didnt got my bow or key back

**Comment by iZoomPvP** [comment]
i can help you get a bow and i will give you a few spider keys as i have 7

**Comment by iZoomPvP** [comment]
i just dont know which bow you had

**Comment by Trixter313** [comment]
If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by iZoomPvP** [comment]
Please help me

**Comment by iZoomPvP** [comment]
I can't finish a quest because I click on Santa to finish the Craftmas Chaos Quest but he doesn't say anything and I can't finish the quest, please help me IGN : iZoomPvP

**Comment by ring0ff1re** [comment]
First off, make a new post as this is completely unrelated to TheLegendOnze's post.
Secondly to answer your problem, look up the quest online to see if you missed anything,
