### ISSUE TITLE
Assassin spin attack not working properly

### ISSUE THREAD

**Issue by yojurriaan** [Wynncraft/Issues#3140]
Since today, 2 skills of assassin are not working properly. Smoke bomb despawns immediatly, and deals no damage. Spin attack throws the enemies in random locations, resulting in the player casting the ability receiving loads of damage. Before, spin attack would stun the enemies. Now they are launched in random directions within the spin attack circle. Please fix these issues, smoke bomb is useless now. Same for spin attack, it instantly kills you if you are grinding with lots of mobs nearby.

**Comment by monkeybug34** [comment]
I'm suprised that this hasn't been fixed yet. hasnt there been a few patches allready?

**Comment by SioN-wynncraft** [comment]
I have 1 think to add: now spin attack damages more then total multihit and it stuns mind for a little

**Comment by SioN-wynncraft** [comment]
*mobs

**Comment by Trixter313** [comment]
Well, the smoke bomb appears to be fixed now. Multihit still acts crazy though.

**Comment by yojurriaan** [comment]
Yup.
Op 7 jan. 2016 08:45 schreef "Nick Cipriani" <notifications@github.com>:

**Comment by SioN-wynncraft** [comment]
Spin attack is fixed too :)

**Comment by Trixter313** [comment]
It is for you? Mobs still get thrown all around for me.

**Comment by yojurriaan** [comment]
Spin attack is still bugged. Multi hit and smoke bomb are fixed. Though
multi hit is worse now since it moves the enemies up during the spell,
disabling you from recasting it on the same enemy.
Op 8 jan. 2016 23:11 schreef "Nick Cipriani" <notifications@github.com>:

**Comment by SioN-wynncraft** [comment]
Yes I look 5 days ago and everything working well
(I am a ninja)

**Comment by abschlepper** [comment]
Spin attack still doesnt work for me

**Comment by ShaGZCl1** [comment]
(Spin attack) and (Multi hit spell) let mobs still get thrown all around now.

**Comment by SmileyAlec** [comment]
They said that they fixed the assassin spells but they still havent fixed
spin attack
Op 25 jan. 2016 13:29 schreef "ShaGZCl1" <notifications@github.com>:

**Comment by Trixter313** [comment]
I just tested spin attack out and for me at least, it's no longer doing any damage to me and most of the time flings the mob away from me now. Sometimes it will spin around me then get flung but that might be intended. I can't get it to hurt me any more though and it it's no longer constant so I'd say the issue is fixed. Can anyone else comment? Thanks!

**Comment by MassAttack** [comment]
Spin attack is still broken, just sends enemies flying away. Hope this isn't intended because it makes grinding almost imposible because it sends enemies too far away and if it doesn't kill they'll despawn

**Comment by ShaGZCl1** [comment]
Why is this skill change into "push".
This change not better "pull"

**Comment by Trixter313** [comment]
Fixed! =)
Proof: https://youtu.be/CiXq_8fEFCE
