### ISSUE TITLE
Ragni Guard.

### ISSUE THREAD

**Issue by Shucklee** [Wynncraft/Issues#4195]
One of the Ragni's guard keep attacking ppl all the time (including me). Can u fix that Issue/problem?
![2016-02-20_19 10 41](https://cloud.githubusercontent.com/assets/17361035/13198385/cbce2cae-d807-11e5-9108-7c6a8b7fa3e8.png)

**Comment by Odnod** [comment]
This has been an issue as long as Gavel has been out. It is an issue with the AI and cannot be resolved too simply.

**Comment by TrashcanMan** [comment]
@Odnod Actually I think it should be pretty easy to fix, it appears that they just assigned it the wrong AI (hostile AI instead of friendly AI).

**Comment by HaveThomeCandy** [comment]
they usually stop if you leave Ragni

**Comment by Shucklee** [comment]
He will follow you until you are out of his range. :)
21. feb. 2016 09:05 skrev "HaveThomeCandy" <notifications@github.com>:

**Comment by AckroWynn** [comment]
@TrashcanMan
Actually, whenever it's a Guard or Ally, it receives a blue name, which means it is not a GM's fault. There is something wrong with this one particular mob's AI, which can only be solved by Jumla.

**Comment by DarkDemonDragon** [comment]
@TrashcanMan it happens randomly. In Ragni Outskirts where there are a bunch of guard NPCs roughly 1 out of 5 will become hostile if you attack them. Considering that most players are under lv 3 at this point that can be deadly. I'm not sure if specific mobs have a messed up AI or the AI in general is broken, but it's not a simple issue.

**Comment by Blocktopia9** [comment]
I think it's because they're neutral mobs

**Comment by Moe-Ronickah** [comment]
Just a note: the issue is still going on.

**Comment by XavierEXE** [comment]
This is still an issue, but the guards don't seem to do any damage to the player.

**Comment by Moe-Ronickah** [comment]
Now, if they would just leave Bob's ghost alone.
