### ISSUE TITLE
Wyncraft excavation site A

### ISSUE THREAD

**Issue by CosmicHero** [Wynncraft/Issues#4293]
I didnt know at the time but when i was about to finish the quest, the server restarted. Now Excavator Vade says go to the lab tent and talk to Tesha, then she says to go talk to Excavator Vade and he tells me the same thing. Some one help me. Now i cant do any of the others.

**Comment by Odnod** [comment]
Try going back through the quest. Go back through the entire pyramid and redo everything.

**Comment by TrashcanMan** [comment]
Try /fixquests

**Comment by NeyRisson** [comment]
I have the same problem, and there has been no problem with the server. Go back to the pyramid and do /fixquests is useless because Vade want me to talk to Tesha and there is no quest item.

**Comment by PenguinInSnow** [comment]
Had the same problem but I figured out how to fix it, thanks to someone who replied to me for the same problem. Basicaly what you need to do is go kill the boss again, go threw the site an other time and make sure when you kill the boss at the end, it give you the ''Yellow glass item''
When you have the item, go back to Excavator Vade and it should be working.

**Comment by Moe-Ronickah** [comment]
@CosmicHero , were you missing the Yellow Crystal, or is the quest still broken for you?

**Comment by XavierEXE** [comment]
#3351

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
