### ISSUE TITLE
the skill point

### ISSUE THREAD

**Issue by silent10901733** [Wynncraft/Issues#4642]
The skill pont always lost it by them self and let me cant use the armor and then lost it

**Comment by Trixter313** [comment]
Try typing /class and reselect your class. This should fix it. Thanks!

**Comment by silent10901733** [comment]
I try it cant

**Comment by Trixter313** [comment]
Could you explain your issue a little more?

I assumed you meant your skills were reset to 0 but did you mean that some skill points appear missing? If so, most over all of your skills and look near the bottom for a message that says it's being modified by your armor. Some armors can add it subtract skill points. That might be what is happening here. You can check all of your armors to see which are subtracting or adding points to skills.

Does this solve your issue? Thanks!

**Comment by silent10901733** [comment]
They  skill point is disappear some and it let me cant wear some armor and then th e is disappear

**Comment by Trixter313** [comment]
I'm still not exactly sure what the issue is. Did you check your armors? Try taking all of your armor and accessories off and then look at your skill points.

If that doesn't help, could you please post a screenshot of your skill point menu? Thanks!

**Comment by Moe-Ronickah** [comment]
I will bet that this is the Zero-skill point bug.  All of your skill points reset to zero, and your armor came if, didn't it?  By now, you have logged off and back on.  You can also use /class to reset your skill points to what they were.

**Comment by Trixter313** [comment]
So is your issue resolved now @silent10901733 ? =)

**Comment by CoolBlueDragon** [comment]
Yes I know what he means. I am currently level 40 but I have lost a few Skill points. As you see in the photo I only have 54 skill points out of my 78 I should have. Not sure what happened, but I have seemed to lose skill points after switching classes. I tried a skill reset scroll and yet I still have the same problem. @Trixter313 
![wynnglitchsp](https://cloud.githubusercontent.com/assets/16386561/14407486/9e6f25bc-fe7f-11e5-8fd5-d76d558f2af6.PNG)

**Comment by Trixter313** [comment]
Did you check with all your armor and accessories off @CoolBlueDragon ?

**Comment by CoolBlueDragon** [comment]
Ah that seems so have fixed it! Thank You @Trixter313

**Comment by Trixter313** [comment]
Glad to hear =)

**Comment by CoolBlueDragon** [comment]
Hmm, Whenever I try to put armor on again seems it resets back. Sorry bout giving trouble about this @Trixter313

**Comment by Trixter313** [comment]
Your armor is affecting your skill points. You should see minus or plus certain skills when you mouse over the armor pieces and a tag on your skill points that said they are being affected by your armor. This is just a feature in the game.

**Comment by CoolBlueDragon** [comment]
Yes, I see this Now. Found with my helmet has been effecting me. Thank You. I'm glad you found my problem :)

**Comment by Trixter313** [comment]
Glad I could clear the confusion =)

**Comment by Trixter313** [comment]
The OP hasn't responded in 16 days, so I'm going to close this issue. If it's still happening to you, simply comment and I'll reopen the issue. Thanks!
