### ISSUE TITLE
Class Error "There has been an error, try again.."

### ISSUE THREAD

**Issue by SkaiiZ** [Wynncraft/Issues#5418]
Hello! I was going to play on this server with my friends, but this strange message appeared when I tried to choose a class. https://gyazo.com/ea01fca00a1f323a066c2f602616e755 I've tried all of the classes, but none of them seem to work. Please fixed this, and my minecraft username is IanVX.
- Ian

**Comment by Moe-Ronickah** [comment]
It's back.  Again.
Sometimes this error fixes itself in an hour or two.  If you are still getting the error, try these, below.
Try deleting the server IP, closing MC, reopening MC 10 min later, then put the server IP back in.
If that doesn't work, make certain that your launcher is up to date.
If that doesn't work, try uninstalling and reinstalling MC.

**Comment by SkaiiZ** [comment]
I have done of all these, nothing worked :(

Is my player data corrupted or something..?

**Comment by Moe-Ronickah** [comment]
I don't believe that your data is corrupted.
Go into your MC files, go to server-resource-packs, and delete the legacy file.  That's the Wynncraft resource pack.  Then, go back and try to login to a class.  Let's see if your resource pack somehow got corrupted when it was downloaded.

**Comment by SkaiiZ** [comment]
Still didn't work, and now i'm starting to lose hope.

**Comment by Moe-Ronickah** [comment]
Don't give up hope.  I'm still researching this one, and our other commenters haven't weighed in on it, yet.

**Comment by XavierEXE** [comment]
I do remember a bug a few players had a while back where there player data was in fact corrupted, that might be what happened here. It is possible to reset your player data, so that can always be a last resort option.

**Comment by SkaiiZ** [comment]
Well thanks for the help, guess I can't play with my friends for the mean time.

**Comment by rzsenseio** [comment]
i'm having the same problem, but have never played. It's a big problem when i tried to do some research on google, why aren't there any solutions?? :/

**Comment by sammyvsparks** [comment]
@rzsenseio please make a new issue and we can help investigate.

**Comment by Moe-Ronickah** [comment]
@rzsenseio , you are correct, it is the same problem.  With your better description in the issue that you opened, it's obviously the same issue.

**Comment by Gregoryus** [comment]
Having the same problem but it's not my first try on addempting to play on this server. Been trying playing for a year !

**Comment by Moe-Ronickah** [comment]
This is a generic message, to everyone affected by these issues.
I've discussed this with the admins, and it turns out, after a lot of investigation, that the 
problem lies within the saved data file created by Minecraft.  The data is corrupted.  For some
of you, your character data files are so badly corrupted that you cannot login and play on any
classes.  For some of you, only one, or maybe two, of your classes, are corrupted.

Well, here is what we can do, and you need to think seriously about the options that I am going
to tell you about, and what they mean.  First, our only possible fix for this is to WIPE your
character.  That means that ALL of your classes will be gone, along with ALL of your information.
That means EVERYTHING will be gone.  Any pets that you purchased, any unused item bombs, any
unused XP bombs, and any GC that you may have left, will be gone.  There is NO way that we
can recover that information before the wipe, so once it happens, there is absolutely no way
to go back and get it, either.  It just cannot be done.  The data file is corrupt.  We can,
however, go back through the store and recover your rank, if you have purchased one.  Your
VIP/VIP+ rank can, and will, be recovered.

So, here is your decision to make.  If you want to keep waiting to see if Minecraft ever will
make a tool to recover lost character information, and they haven't yet made one to recover
lost or corrupted worlds, you can keep on waiting.  Seriously, it's not a problem for us, as
it requires that we simply do nothing to your game account.  For those of you who have lost one
or two classes, the decision to wipe EVERYTHING means that you have to accept the fact that
you will lose ALL of your classes, ALL of your pets, if you purchased any, any bombs that
you may have, and any GC that you may have.  None of this is recoverable if your account is
wiped, however, you will be able to start over on all of your classes.

For those of you who cannot play on any class, you have the same decision to make for yourself.
  You can wait to see if Minecraft will ever make a tool to recover lost character data, with
the same considerations as above.  Minecraft has never made one, and there is nothing that
we have heard of to say that they ever will.  Or, you can choose to have all of your character
data wiped, with the same losses as explained, above, and we can, and will, recover your VIP/VIP+
rank.

So, for each of you, individually, let me know what you want us to do, and I'll pass along your
decisions to the admin, at the end of this week (Friday or Saturday).

**Comment by CureForMadness** [comment]
Hey Moe! I hope you are still reading in this thread. I have this same problem and need that rest. Although I currently have vip+ and would be very great full to keep it. If you can help me out let me know please. My mc name is the same as the one here

**Comment by Moe-Ronickah** [comment]
@CureForMadness , noted.

**Comment by lkjfdsaofmc** [comment]
Moe I if you're still reading this thread I need a reset too, I've had the bug since I first logged in so I won't be losing any items or ranks, IGN: lkjfdsa

Lemme know if I need to login ingame to prove im actually me or something

**Comment by rzsenseio** [comment]
@Moe-Ronickah , are you resetting our characters anytime soon? :/

**Comment by Moe-Ronickah** [comment]
Lady's and gents, I gave you one week, got no responses, and got busy with other things.  HOWEVER, don't worry, I'm gathering names together to pass on to admin for full resets.

**Comment by Moe-Ronickah** [comment]
BUT I NEED YOUR IN-GAME NAME AND YOUR MINECRAFT NAME SO THAT WE DON'T RESET THE WRONG PLAYERS!!

**Comment by CureForMadness** [comment]
I feel like my ign and minecraft name are the same thing. Just CureForMadness

**Comment by lkjfdsaofmc** [comment]
Moe, my IGN is lkjfdsa    (thats a lower case L at the beginning) and my minecraft name should be the same... not sure what you meant by that either, i can login on the server if you want though i can only really access the hub, if you want me to prove who i am :)

**Comment by rzsenseio** [comment]
@Moe-Ronickah my minecraft's name is zHatred, no mistakes on spelling

**Comment by Gregoryus** [comment]
I guess you ask for our minecraft login username and our minecraft nickname, right ?
If so,
my login username is : heroes-78@live.fr<mailto:heroes-78@live.fr>
my nickname is : Gregoryus

PS: I changed my pseudo a while ago from Gregorius78 (old) to Gregoryus (actual)

Le 23 oct. 2016 à 21:49, CureForMadness <notifications@github.com<mailto:notifications@github.com>> a écrit :


I feel like my ign and minecraft name are the same thing. Just CureForMadness

-

**Comment by Celsonic** [comment]
unfortunate... lots of play time wasted for some people, but hey what can you do ;-;

**Comment by LordHelmchen98** [comment]
In the Hallowynn changelog thread Salted mentioned this: "Fixed a bug where some classes wouldn’t load".
I'm not 100% sure but in my opinion it sounds like he was talking about the error messages. Are your classes working now or do you still get the error messages.

**Comment by lkjfdsaofmc** [comment]
I've checked mine about a dozen times since the update, no fix, according to some staff the update that will add the hero rank MAY fix the bug for SOME people, but i'd really rather in my case for them to just wipe it immediately, considering I never once got to play on this account so i'll lose absolutely nothing, I'd just like access to it ASAP.

**Comment by redsoxno10** [comment]
I have no idea if this is an outcome of it, but it has been spitting out blank lines for no reaason
[http://i.imgur.com/P7n6GPj.png](image)

**Comment by AuburnTigerFan55** [comment]
I was having the same problem as everyone else, (#6309) ,but I logged in today and it was fixed. I don't know if there was an update or by random chance it worked, but my level 49 mage class is back to normal now.

**Comment by lkjfdsaofmc** [comment]
There were some theories that the store update would fix the bug, it didn't for everyone, glad it did for you though

**Comment by CureForMadness** [comment]
So it's still broken for me what's going on?

**Comment by Gregoryus** [comment]
Same for me here, still not fixed.


Le 6 nov. 2016 à 21:01, CureForMadness <notifications@github.com<mailto:notifications@github.com>> a écrit :


So it's still broken for me what's going on?

-

**Comment by Moe-Ronickah** [comment]
OK, EVERYONE AFFECTED:
There have been several updates, and a rank addition, this is why the delay ultimately occurred in wiping any player data.  Therefore, ONE WEEK from today, I will send the list of anyone who signs up, **below**, to have their account wiped.  Take it or leave it, folks.

**Comment by CureForMadness** [comment]
Great! Thank you. Again the name os the same as my name on here: CureForMadness

**Comment by Gregoryus** [comment]
Wipe my account pls,
Gregoryus or Gregorius78 (previous username)


Le 17 nov. 2016 à 01:34, Nathan Stolov <notifications@github.com<mailto:notifications@github.com>> a écrit :


OK, EVERYONE AFFECTED:
There have been several updates, and a rank addition, this is why the delay ultimately occurred in wiping any player data. Therefore, ONE WEEK from today, I will send the list of anyone who signs up, below, to have their account wiped. Take it or leave it, folks.

-

**Comment by redsoxno10** [comment]
Are you saying that our "corrupted" accounts are already wiped, and you are asking us if we want them wiped? Or are you saying that the classes are gone forever and cannot be retrieved, so you are asking us for our usernames?

**Comment by ColinRioux** [comment]
Moe is saying that if your account is corrupted, and you would like it wiped, list your IGN as a comment next to the words: "Wipe my account". 

If you are getting these errors, as explicitly stated above, your account data is corrupted. Corrupted in this case means: unretrievable. So yes, your classes which throw an error are gone forever. The only way to fix it is to wipe all data associated with your account on the Wynncraft servers. 

Should I be any clearer?

**Comment by rzsenseio** [comment]
Wipe my account, username zHatred

**Comment by redsoxno10** [comment]
ok. Then wipe my WARRIOR CLASS ONLY, ign: Sudoman

**Comment by Trixter313** [comment]
@redsoxno10 I'm pretty sure that in this situation everything would have to be wiped, with no option of just a certain class, unfortunately.

**Comment by rzsenseio** [comment]
its been a week?

**Comment by Moe-Ronickah** [comment]
@redsoxno10 , your request cannot be done.  Read my post of Sept 25.  This is an all or none situation.

For those of you still waiting, THIS is why the delay has occurred; some people just do not bother to read everything carefully.  @redsoxno10 , your data will remain.  We will not wipe your data.

**Comment by redsoxno10** [comment]
I said that **6 days** after you said that. I believe that is before one week after you said that. It is within your deadline.

**Comment by CureForMadness** [comment]
@redoxno10 I think what Moe is saying is that they can not only wipe one of your classes. It's all or nothing. 

Also, I checked my account yesterday and I still can't sing into a character. You said we had a week to get names submitted here. That was 12 days ago now and it's still not working. Do they need more time? Have they not gotten to it? Basically can we get an update?

**Comment by rzsenseio** [comment]
Why is there no progress whatsoever?

**Comment by CureForMadness** [comment]
So.... nothing huh? Great.

**Comment by Jonzka** [comment]
Hello @Moe-Ronickah please wipe my account on Wynncraft also, i have the same problem as the ppl here

My minecraft name is: Jonzka

**Comment by rzsenseio** [comment]
Apparently, @Moe-Ronickah is contributing to other several posts, but doesn't respond to this particular one.

**Comment by EmfMC** [comment]
Hello, I'm unsure if this thread is still being read by staff but if it is I would like to request that my player data be wiped. I have been unable to play on the server at all with my account and have just found this thread. I understand that all my player data on the server will be erased and I will be unable to get it back. Thank you for taking the time out of your day to read this. (My MineCraft user name is EmfMC)

**Comment by Moe-Ronickah** [comment]
Gregoryus
CureForMadness
zHatred
Jonzka
Your player data has been reset.

**Comment by Iannbeas** [comment]
@Moe-Ronickah 

Are you still able to reset my data?

**Comment by LordHelmchen98** [comment]
@Iannbeas check #7185

**Comment by Herugaa** [comment]
Hello @Moe-Ronickah !
Can you wipe my account on Wynncraft, I have the same problem as all the peoples here....

My name on Minecraft : DoTheWasshingUp

**Comment by Herugaa** [comment]
plizzzzzzzzzzzzzzz restet me

**Comment by LordHelmchen98** [comment]
@Herugaa please post it on #7185
