### ISSUE TITLE
Wynnexcavation Site  C

### ISSUE THREAD

**Issue by OlavAleks** [Wynncraft/Issues#5424]
I'm at WynnExcavation Site C quest and I need to report back to Placardus and it says I need the Purple Crystal Shard from Site B to start this quest but I already have it and when I do /fixquests it gives me 2 more of it and still does not work.

**Comment by Moe-Ronickah** [comment]
Would you [read this](https://wiki.wynncraft.com/index.php?title=WynnExcavation_Site_C), in the Wiki, and tell us exactly where you are at in the Site C quest?  You are describing NPC interactions that appear to be from both Stage 1 and Stage 9, so I'm really confused as to what is happening.

**Comment by OlavAleks** [comment]
Done Stage 1, 2, 3, 4, 5, 6 and 7..

As I read the Wiki I have forgotten to bring with me a crystal shard. I will try again to get one and talk to him..

**Comment by OlavAleks** [comment]
But in my quest book it says report back to the guy?

**Comment by OlavAleks** [comment]
Okay, so the problem was I didnt get the red crystal shards.

My bad.

**Comment by OlavAleks** [comment]
But it somehow skipped Stage 8..

**Comment by XavierEXE** [comment]
What must have happened is you went through the quest but in the room where the crystal shards drop, you forgot to pick one up before you went through the teleporter, and the quest updated anyways. Going back through the quest and getting a crystal shard should fix the issue.

**Comment by Moe-Ronickah** [comment]
"But it somehow skipped Stage 8."  Stage 8 is an "informal" step, insofar as the quest logic expects that if you follow what Amadel tells you to do, that you will get the crystal shard, before you leave.  The game doesn't check to see if you did get the shard.
