### ISSUE TITLE
Morph Set Bonus not given correctly

### ISSUE THREAD

**Issue by JackyKit123** [Wynncraft/Issues#6283]
I discover this bug that set bonus for morph is not given when the certain pieces are equipped.
As seen in the first pic my skill points on strength is 21
http://i.imgur.com/Wgkc3zK.png
My morph-ruby gives +3 Strength
http://i.imgur.com/khc41ZM.png
When I equip morph-ruby, it should gives '21(original) + 3(from the item itself) + 1(set bonus) = 25 Strength'
http://i.imgur.com/WYM4dmG.png
But when I check my skill points, it show 24 Strength
http://i.imgur.com/IN4VdDl.png
This should not be a display error since Prism requires 25 Strength to Equip and it shows a cross at Strength Min:25
http://i.imgur.com/hldMGja.png
Please leave a reply if there is any unclear part

**Comment by Moe-Ronickah** [comment]
It shows a red "X", meaning that you don't have enough Str.

**Comment by JackyKit123** [comment]
That is something that should NOT happen
I started with 21 strength while wearing morph-amethyst, which means
When I equip morph-ruby with 3 strength points
it should gives +3 +1 from the 2-piece set bonus which also means I am supposed to have 25 strength instead of 24 strength only so it is supposed to show a tick on strength min 25 not a cross
What I discover is the set bonus of skill points is not given correctly

**Comment by JackyKit123** [comment]
no I do not, all I did was put on a morph-amethyst in the first pic
and then I put on morph-ruby
I wore nothing else

**Comment by Moe-Ronickah** [comment]
Hey, Jacky, try changing the order that you put the items on tell us what happens.  I don't have anything close to a full morph set, so I can't test this.

**Comment by JackyKit123** [comment]
Moe, I was only using 2 pieces of morph items
(morph-amethysy and morph-ruby)
the 2-piece set bonus for morph item should give
+1 Str
+1 Dex
+1 Int
+1 Def
+1 Agi
but none of these were given when I put 2 piece on

**Comment by Moe-Ronickah** [comment]
@AckroWynn , can you test this on the build server?

**Comment by DavicusPrime** [comment]
I was just realizing this same issue and I'm running with 6 Morph Set Items:  I didn't have a chance to collect any Screen Grabs but I scribbled everything down on scratch paper and made the attached handy-dandy(tm) Spreadsheet.  
![davicusprime1 archer skill calculations 12-05-2016](https://cloud.githubusercontent.com/assets/22798780/20891616/24918764-bac0-11e6-9eab-94e7f244086f.PNG)

I use a Spiritshock Bow that requires 80 Dex and the game would not allow it's use until I put enough skill points to cover the missing Set Bonus.  This makes me wonder if the Set Bonuses are just failing to be included in the displayed skill level or if they have failed to be included at all in the the behind the scenes math.

I haven't checked to see if the other non-skill related bonuses are being added correctly.  But the last time I skimmed the Character stats in game, they didn't seem to match what I expected them to be.  I didn't think to much about that since I had read elsewhere on the forums that those stats haven't displayed correctly for a while.  I could look into whipping up another handy-dandy(tm) spreadsheet for that tomorrow if that would be helpful.

I have a set of Visceral Armor handy such that I could equip it to test if this is a Set Bonus issue in general or if it's particular to the Morph Set Items as well.

What other information would you find helpful?

-DavicusPrime

**Comment by DavicusPrime** [comment]
Has there been any movement on this one?

**Comment by JackyKit123** [comment]
it is still bugged for now
my morph set skill points bonus are still not recieved

**Comment by DavicusPrime** [comment]
I decided to test a theory:
Hypothesis = the set bonus isn't being applied because not every skill is not up to the minimum of the highest level piece.

I reset my skill points and re allocated them to have the minimum for my highest item (15) in each.  

Zero effect.

I'm about to hit level 87 where I can add item #7.  If this bug isn't resolved by then, I'll be getting robbed of 55 extra skill points.

Still haven't fully confirmed it but the other set bonuses appear to show up correctly.  So this seems to be skill points to related only.

-DavicusPrime

**Comment by Moe-Ronickah** [comment]
I now have all but one piece of the morph set, and I'm not wearing one piece, yet.  I can now validate, as has everyone else, but through removing all of my armor, accessories, and weapons, just what is happening.  The morph set has multiple bonuses to health, skills, xp, exploding, reflection, loot, and all elemental damages.  Everything works EXCEPT for the skill point bonuses, of which, none are applied, at any level of added set pieces, at least up to and including the 6th piece.  So, between DavicusPrime's table, and mine, I will now pass this along with a great big CONFIRMED.

**Comment by DebugMC** [comment]
I think this is fixed. I wear the full morph set and am getting the bonuses now.

**Comment by Moe-Ronickah** [comment]
@DebugMC , please show us a table, such as the one DavicusPrime made, with your data.

**Comment by JackyKit123** [comment]
@Moe-Ronickah 
To make thing simple
Here's my setup
Str 20
Dex 20
Int 20
Def 20
Agi 20
Ok then I put on morph amethyst
Which give +3 +3 +3 +3 +3
My skillpoints become
23 23 23 23 23
Next I put on morph ruby
Which give +3 +3 +3 +3 +3
My skillpoints become
26 26 26 26 26
Which should have been   
27 27 27 27 27
Proving the the set bonus +1 +1 +1 +1 +1 is still not added
This glitch still exists

**Comment by Moe-Ronickah** [comment]
@JackyKit123 , that's why I asked @DebugMC  to show us his data, if he is claiming that this has been fixed.

**Comment by DavicusPrime** [comment]
Just checked this again with 7 Morph Items...  Still Broken.  What is the priority on sorting this out?

-DavicusPrime

**Comment by Moe-Ronickah** [comment]
I haven't heard anything about it.  It may be coming with the code update, it may be on it's schedule.  All I have are maybes.
