### ISSUE TITLE
Hunger of Gerts part II not working

### ISSUE THREAD

**Issue by NinjaPiggy** [Wynncraft/Issues#7152]
So, I'm at the stage of the quest where the Captured Gert asks you to go and turn off the power. But, when I try to leave:
![screen shot 2017-01-09 at 6 32 12 pm](https://cloud.githubusercontent.com/assets/17673269/21866169/08be758c-d817-11e6-893c-dd1e6ae1b67a.png)
I can't. I also am unable to talk to the Captured Gert, as nothing happens when I right-click him. Help?

**Comment by LordHelmchen98** [comment]
Try to talk to him from different angles and not through the iron bars. Sometimes it takes some time to get him to speak to you.

**Comment by DohdoEXE** [comment]
I got this issue to. I fixed it by doing /kill and redoing the quest from when you enter the basement

**Comment by XavierEXE** [comment]
Walk back to the stairs at the beginning of this room, and walk down the stairs without jumping or sprinting, you most likely accidentally skipped the tripwire that triggers the next stage of the quest.

**Comment by NinjaPiggy** [comment]
Okay, I tried everything, nothing's happening. Please note that my quest book IS updated to "Turn off the power at [-1011.18,-7870].

**Comment by AscendedKitten** [comment]
As others already suggested, try to trigger the next stage (which doesn't necessarily update the quest book message) by going back and entering again. If that doesn't solve it, try exiting and completing the whole path again.
