### ISSUE TITLE
Stuck... But wait there is more.

### ISSUE THREAD

**Issue by mickyds33** [Wynncraft/Issues#7970]
(NOTE I AM USING THE Wynncraft Enhanced modpack on curse.) So I was going from Nemract to Selchar VIA the ship fast travel option, and I hit the button below the clock because why not, I had no idea what it would do at the time, and it did not work and I taught it was just a random button, So a few seconds later I d/c because Australian internet and upon logging on I find myself at the Selchar dock rubber banding in the air and when I turn it turns me back almost like when you are loading in, and I the texture pack loads and I am intently kicked int the lobby for "Flying is not enabled." and so I look up this bug and I found the /kill method and upon doing this it did not work for whatever reason. And so I get booted into lobby yet again and try again thinking the command went through and I was lagging, but yet again another failure, I cannot change characters because I have auto log in set to this character. I have no idea if this happened because I d/ced med fast travel or if it was due to the button but I'm stuck and cannot seem to find a method to getting un-stuck.

Also a few minutes later after I finishing writing this I get the following message when I try log in Wynncraft overall. : https://gyazo.com/2c294b60d7a55edb86f6f7d8f7d898eb I will update you if this fixes itself.

**Comment by thecoolkogut4** [comment]
Try to turn off auto join, then once you spawn in try to do /kill again.

**Comment by mickyds33** [comment]
Update: The Error: "Could not connect to a default or fallback server, please try again later: Io.Metty.channel.AbstractChannel$ AnnotatedConnectException" is stillgoing on and I am unable to join Wynncraft in particular on this computer. I have just attempted to join a 1.10 server and I was able to get in just fine it seems wynncraft is the only server doing this. Not sure if it's on mine or server end.

I will get on my little brother's computer and see if I can get 'thecoolkogut4" 's method to work, I will keep you updated on that.

**Comment by thecoolkogut4** [comment]
Also, try to log in without wynnenchanced. Another thing you ca  do to fix that error is keep on trying to log in. I believe that error is because the hub server your trying to connect to is down (eg your trying to connect to hub #5 when only 1-3 are open) just keep on trying to connect and it should fix itself, if not wait a few minutes then try again.

**Comment by mickyds33** [comment]
Thanks thecoolkogut4, the 'stuck' glitch fixed itself I just logged onto my brother's computer and logged into my account and I feel onto the dock when I logged in, so basicly that issue is fixed

I will do as you recommend and keep trying to log in, fingers crossed.

**Comment by mickyds33** [comment]
Yet another update:  Now both computers are getting this error. Yes, I know I was just logged in on my brother's computer but I logged off to type what I typed above and tried to log in again and got the same error on his computer, I then logged onto his account (He has it autologged in.) and he got the same error aswell.

**Comment by mickyds33** [comment]
Okay, Iv been trying for about 1 hour and a half now while watching youtube and nothing has happened still getting the same error.

**Comment by thecoolkogut4** [comment]
There's also the possibility of changing the ip

So try connecting with
Play.wynncraft.com
Play.wynncraft.net
Build.wynncraft.com
Gm.wynncraft.com
Test.wynncraft.com
Randomstuffhere.wynncraft.com

**Comment by mickyds33** [comment]
Build.wynncraft.com worked for some strange reason.

**Comment by mickyds33** [comment]
Thank you for your help, I'm sure this is only a temporary fix but it's great to be able to get on, Thank you so much for your help thecoolkogut4.

**Comment by thecoolkogut4** [comment]
It's a temp fix, after a while try to connect with the normal ip.

**Comment by mickyds33** [comment]
Will do, you have helped big time if it happens again I will post a new bug report thank you for now I will close this :)
